import type { PulpitKit } from '@/lib/types';

/**
 * Pure formatting helpers for the pulpit kit. Kept free of the Supabase client so
 * client components can import them without pulling the database SDK into the
 * browser bundle.
 */

const DEFAULT_MINUTES = 35;

/** Formats a `YYYY-MM-DD` or ISO timestamp into a human-readable date. */
export function formatKitDate(value: string): string {
  if (!value) return '';

  const isDateOnly = /^\d{4}-\d{2}-\d{2}$/.test(value);
  const date = new Date(isDateOnly ? `${value}T00:00:00` : value);
  if (Number.isNaN(date.getTime())) return value;

  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
}

/** Estimated teaching length, derived from the outline when the DB omits it. */
export function estimateKitMinutes(kit: PulpitKit): number {
  if (kit.estimated_minutes !== undefined && kit.estimated_minutes > 0) {
    return kit.estimated_minutes;
  }
  if (kit.outline.length > 0) return kit.outline.length * 12;
  return DEFAULT_MINUTES;
}

/** Formats the whole kit as Markdown for Obsidian, Notion, or Google Docs. */
export function buildPulpitKitMarkdown(kit: PulpitKit): string {
  const lines: string[] = [];

  lines.push(`# ${kit.title}`, '');
  if (kit.theme) lines.push(`**Theme:** ${kit.theme}`);
  if (kit.series_name) lines.push(`**Series:** ${kit.series_name}`);
  if (kit.scripture_passages.length > 0) {
    lines.push(`**Scripture:** ${kit.scripture_passages.join('; ')}`);
  }
  lines.push(`**Teaching Length:** ${estimateKitMinutes(kit)} minutes`);
  if (kit.target_sunday) lines.push(`**Target Sunday:** ${formatKitDate(kit.target_sunday)}`);
  lines.push('');

  if (kit.outline.length > 0) {
    lines.push('## Sermon Architecture', '');
    kit.outline.forEach((point, index) => {
      lines.push(`${index + 1}. **${point.section}**`);
      if (point.subtext) lines.push(`   - ${point.subtext}`);
    });
    lines.push('');
  }

  if (kit.talking_points.length > 0) {
    lines.push('## Talking Points', '');
    kit.talking_points.forEach((point) => lines.push(`- ${point}`));
    lines.push('');
  }

  if (kit.scripture_passages.length > 0) {
    lines.push('## Core Scripture', '');
    kit.scripture_passages.forEach((passage) => lines.push(`> ${passage}`));
    lines.push('');
  }

  if (kit.discussion_questions.length > 0) {
    lines.push('## Community Group Study', '');
    kit.discussion_questions.forEach((question, index) => lines.push(`${index + 1}. ${question}`));
    lines.push('');
  }

  if (kit.key_quote) {
    lines.push('## Key Quote', '', `> ${kit.key_quote}`, '');
  }

  if (kit.call_to_action) {
    lines.push('## Application Challenge', '', kit.call_to_action, '');
  }

  lines.push('---', '', '_Generated by the JesusUnited Pulpit Kit Generator._');

  return lines.join('\n');
}